### ISSUE TITLE
The install.cmd dont run

### ISSUE THREAD

**Issue by Bigotitos05** [thisneq/interiorproxies_creator#1]
I install the creator and when I run start de install.cmd dont runs so I need help (sorry for my english)
Cuando ejecuto el install,cmd no abre , no se lo que pasa sii me podriais ayudar, Gracias

**Comment by Ioannis-Toptsis** [comment]
Press Enter.

**Comment by BaziForYou** [comment]
> I install the creator and when I run start de install.cmd dont runs so I need help (sorry for my english) Cuando ejecuto el install,cmd no abre , no se lo que pasa sii me podriais ayudar, Gracias

install node.js lamo its so late to answer

**Comment by juppjup01** [comment]
not working for me? have tried to run and do it on node and both just giving errors

**Comment by BaziForYou** [comment]
> not working for me? have tried to run and do it on node and both just giving errors

what error you get?

**Comment by tibor82** [comment]
Helo. This problem for me, my server and map.
Not installing.
No errors no nothings, just not instal, and not work.
